// Fill out your copyright notice in the Description page of Project Settings.

#pragma once

#include "CoreMinimal.h"
#include "Kismet/BlueprintFunctionLibrary.h"
#include "TongSimGameplayFunc.generated.h"

class ATSWorldSettings;
/**
 *
 */
UCLASS()
class TONGSIMGAMEPLAY_API UTongSimGameplayFunc : public UBlueprintFunctionLibrary
{
	GENERATED_BODY()

public:
	/* Basic */
	UFUNCTION(BlueprintPure, Category = "TongSim|Basic", meta = (bIgnoreSelf = "true", DisplayName = "Generate A GUID Name"))
	static FName GetGUIDNameForUObject(TSubclassOf<UObject> ObjectClass);

	UFUNCTION(BlueprintCallable, Category = "TongSim|Basic", meta = (bIgnoreSelf = "true", DisplayName = "Add A Component On Instance"))
	static UActorComponent* AddComponentOnActorInstance(AActor* ActorInstance, TSubclassOf<UActorComponent> ComponentClass, bool bAddUnique, bool bAddIfNotChild, bool bUseAutoGeneratedName = false);

	UFUNCTION(BlueprintCallable, Category = "TongSim|Basic", meta = (bIgnoreSelf = "true", DisplayName = "Destroy an instanced component"))
	static bool DestroyInstancedComponent(UActorComponent* Component);

	/* GameMode */
	UFUNCTION(BlueprintPure, Category = "TongSim|GameMode", meta = (bIgnoreSelf = "true"))
	static ATSWorldSettings* GetTongSimWorldSettings(UObject* WorldContextObject);

	/* Input */
	UFUNCTION(BlueprintCallable, Category = "TongSim|Input", meta = (bIgnoreSelf = "true", DisplayName = "Simulate Enhanced Input "))
	static void SimulateEnhancedInputAction(APlayerController* InPC, const UInputAction* InputAction, const FInputActionValue Value);

	/* XR */
	UFUNCTION(BlueprintPure, Category = "TongSim|XR", meta = (bIgnoreSelf = "true", DisplayName = "Is HMD Connected"))
	static bool IsHMDConnected();

	/* NetWork */
	UFUNCTION(BlueprintPure, Category = "TongSim|NetWork", meta = (bIgnoreSelf = "true", DisplayName = "Get Local LAN IP"))
	static FString GetLocalIP();

	UFUNCTION(BlueprintPure, Category = "TongSim|NetWork", meta = (bIgnoreSelf = "true", DisplayName = "Is Client Ready"))
	static bool IsClientReady(const UObject* Context);

	UFUNCTION(BlueprintPure, Category = "TongSim|NetWork", meta = (bIgnoreSelf = "true", DisplayName = "Is Local Distributed Agent"))
	static bool IsLocalDistributedAgent(const AActor* Agent);

	UFUNCTION(BlueprintCallable, Category = "TongSim|NetWork", meta = (bIgnoreSelf = "true", DisplayName = "Kick All Player"))
	static void KickAllPlayer(const UObject* Context);

	/* Rendering Math */
	static void GetViewFrustumVolume(FMatrix ViewProjectionMatrix, FConvexVolume& OutFrustum);

	UFUNCTION(BlueprintPure, Category = "TongSim|Rendering Math", meta = (bIgnoreSelf = "true", DisplayName = "Get Actors in ViewFrustum with AABB-Culling"))
	static void GetActorsInViewFrustumWithAABBCulling(FMinimalViewInfo ViewInfo, int32 DepthBufferWidth, int32 DepthBufferHeight, const TArray<AActor*>& InActors, TArray<AActor*>& OutActors);

	/* High Light */
	UFUNCTION(BlueprintCallable, Category = "TongSim|Highlight", meta = (bIgnoreSelf = "true", DisplayName = "Highlight Mesh"))
	static bool HighlightMesh(UMeshComponent* Mesh, bool bHighlight, float LineThickness = 3.0f, FLinearColor Color = FLinearColor::Red);
};
