name: Bug report
description: Report a problem with TongSIM
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to report a bug.
  - type: textarea
    id: description
    attributes:
      label: Description
      description: What happened?
    validations:
      required: true
  - type: textarea
    id: steps
    attributes:
      label: Steps to reproduce
      description: Minimal steps, commands, or scripts to reproduce the issue.
      placeholder: |
        1. ...
        2. ...
        3. ...
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: Expected behavior
    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      label: Logs / screenshots
      description: Paste logs (use code blocks) or attach screenshots if helpful.
    validations:
      required: false
  - type: input
    id: ue_version
    attributes:
      label: Unreal Engine version
      placeholder: "5.6"
    validations:
      required: false
  - type: input
    id: python_version
    attributes:
      label: Python version
      placeholder: "3.12.x"
    validations:
      required: false
  - type: input
    id: os
    attributes:
      label: OS
      placeholder: "Windows 11 / Ubuntu 22.04"
    validations:
      required: false
